import type { LiveClientAllGameData } from "@workspace/recommender"

export const bundledReplayFixture = {
  activePlayer: {
    currentGold: 1500,
    level: 9,
    riotId: "Coach Player#EUW",
    riotIdGameName: "Coach Player",
    riotIdTagLine: "EUW",
    summonerName: "Coach Player",
  },
  allPlayers: [
    {
      championName: "Jinx",
      items: [
        {
          count: 1,
          displayName: "Executioner's Calling",
          itemID: 3123,
          price: 800,
          slot: 0,
        },
      ],
      level: 9,
      position: "BOTTOM",
      riotId: "Coach Player#EUW",
      scores: {
        assists: 3,
        creepScore: 92,
        deaths: 1,
        kills: 4,
        wardScore: 5,
      },
      summonerName: "Coach Player",
      team: "ORDER",
    },
    {
      championName: "Lux",
      items: [],
      level: 8,
      position: "UTILITY",
      riotId: "Ally Support#EUW",
      scores: {
        assists: 7,
        creepScore: 18,
        deaths: 2,
        kills: 1,
        wardScore: 22,
      },
      summonerName: "Ally Support",
      team: "ORDER",
    },
    {
      championName: "Amumu",
      items: [],
      level: 8,
      position: "JUNGLE",
      riotId: "Ally Jungle#EUW",
      scores: {
        assists: 5,
        creepScore: 73,
        deaths: 3,
        kills: 2,
        wardScore: 8,
      },
      summonerName: "Ally Jungle",
      team: "ORDER",
    },
    {
      championName: "Aatrox",
      items: [
        {
          count: 1,
          displayName: "Ruby Crystal",
          itemID: 1028,
          price: 400,
          slot: 0,
        },
      ],
      level: 11,
      position: "TOP",
      riotId: "Enemy Top#EUW",
      scores: {
        assists: 2,
        creepScore: 105,
        deaths: 1,
        kills: 6,
        wardScore: 4,
      },
      summonerName: "Enemy Top",
      team: "CHAOS",
    },
    {
      championName: "Soraka",
      items: [],
      level: 8,
      position: "UTILITY",
      riotId: "Enemy Support#EUW",
      scores: {
        assists: 9,
        creepScore: 12,
        deaths: 1,
        kills: 0,
        wardScore: 26,
      },
      summonerName: "Enemy Support",
      team: "CHAOS",
    },
    {
      championName: "Zed",
      items: [],
      level: 10,
      position: "MIDDLE",
      riotId: "Enemy Mid#EUW",
      scores: {
        assists: 1,
        creepScore: 97,
        deaths: 2,
        kills: 5,
        wardScore: 3,
      },
      summonerName: "Enemy Mid",
      team: "CHAOS",
    },
  ],
  gameData: {
    gameMode: "CLASSIC",
    gameTime: 910.25,
    mapName: "Map11",
    mapNumber: 11,
    mapTerrain: "Default",
  },
} as const satisfies LiveClientAllGameData
